---
title: "GCalignR step by step"
author: "Martin A. Stoffel & Meinolf Ottensmann"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: bibliography.bib
vignette: >
    %\VignetteIndexEntry{inbreedR step by step}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
library(knitr)
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", cache = FALSE,
    fig.width = 5, fig.height = 4) # warning = FALSE
```


## GCalignR

GCalignR provides a simple means of aligning chromatograms from gas-chromatography (GC)
and gas-chromatography mass-spectrometry (GC-MS). Chromatograms of multiple samples are not
directly comparable as the retention times vary across samples due to sublte, random and often
unavoidable variation the GC-MS machine parameters [@pierce2005classification]. For studies
interested in broad patterns within chemical samples it is crucial that the same substances
will have the same retention times to compare them across samples. Suprisingly, within the
relatively young field of mammalian olfactory communication, most researchers seem to align
chromatograms manually (some citations) rather than using automated alignment algorithms, 
which are used by chemists or chemical plant biologists for a while (i am not sure about this,
needs citations). This might be due to (to what might it be due? No idea, but we also didn´t use
them obviously).

## The alignment algorithm

## Aligning chromatograms with GCalignR

## Literature


