#' Find the best linear shift
#' @description
#' Selects the optimal shifting time leading to the maximum number of shared peaks
#' between a chromatogram and its reference.
#'
#' @param peaks data.frame including a shift value and the corresponding number of shared peaks.
#' Generated by \code{\link{shared_peaks}}
#'
#' @return
#' optimal shift in seconds to yield the maximum number of shared peaks
#'
#' @details
#' If competing shifts exists (i.e. same number of peaks are shared),
#' selects the smallest absolute value of a shift
#'
#' @author Martin Stoffel (martin.adam.stoffel@@gmail.com) & Meinolf Ottensmann
#'   (meinolf.ottensmann@@web.de)
#'
#' @export
#'
best_shift <- function(peaks){

    shared <- as.vector(peaks[[1]]) # Name was confusing, these are the shared peaks
    shifts <- as.vector(peaks[[2]]) # these are the shifts
    index <- which(shared==max(shared)) # find the best fit = maximum of shared peaks
    BestFit <- shifts[index]
    BestFit
    if (length(BestFit)>1){
        temp <- min(abs(BestFit)) # If equal shifts were found, take the smallest shift applied
        BestFit <- BestFit[BestFit==temp | BestFit==temp*-1]
        if (length(BestFit > 1)) BestFit <- BestFit[1]
    }else{
        BestFit
    }
    if(file.exists(paste0(as.character(match.call(definition = sys.function(sys.parent(5)), call = sys.call(sys.parent(5)))["data"]),"_LogFile.txt"))){
    sink(paste0(strsplit(as.character(match.call(definition = sys.function(sys.parent(5)), call = sys.call(sys.parent(5)))["data"]),split = ".txt"),"_LogFile.txt"),append = TRUE)
    cat(paste('\nShift = ',as.character(format(round(BestFit,3),nsmall=2)),'\tShared Peaks = ',as.character(shared[index[1]]))) # Delete later
    sink()
    }
return(BestFit)
}

