#' Find the best linear shift
#' @description
#' Selects the optimal shifting time leading to the maximum number of shared peaks
#' between a chromatogram and its reference.
#'
#' @param peaks data.frame including a shift value and the corresponding number of shared peaks.
#' Generated by \code{\link{shared_peaks}}
#'
#' @return
#' optimal shift in seconds to yield the maximum number of shared peaks
#'
#' @details
#' If competing shifts exists (i.e. same number of peaks are shared),
#' selects the smallest absolute value of a shift
#'
#' @author Martin Stoffel (martin.adam.stoffel@@gmail.com) & Meinolf Ottensmann
#'   (meinolf.ottensmann@@web.de)
#'
#' @export
#'
best_shift <- function(peaks){

    ShiftTime <- as.vector(peaks[[1]])
    Peaks <- as.vector(peaks[[2]])
    Index <- which(ShiftTime==max(ShiftTime)) # find the best fit = maximum of shared peaks
    BestFit <- Peaks[Index]
    BestFit
    if (length(BestFit)>1){
        temp <- min(abs(BestFit)) # If equal shifts were found, take the smallest shift applied
        BestFit <- BestFit[BestFit==temp | BestFit==temp*-1]
        if (length(BestFit > 1)) BestFit <- BestFit[1]
    } else{
        BestFit
    }
return(BestFit)
}

